import { Product } from './store';

export const categories = [
  { id: 'automation', name: 'Automation', icon: 'Settings' },
  { id: 'electronics', name: 'Electronics', icon: 'Zap' },
  { id: 'sensors', name: 'Sensors', icon: 'Radio' },
  { id: 'actuators', name: 'Actuators', icon: 'Move' },
  { id: 'controllers', name: 'Controllers', icon: 'Cpu' },
  { id: 'accessories', name: 'Accessories', icon: 'Wrench' },
];

export const sampleProducts: Product[] = [
  {
    id: '1',
    name: 'Arduino Uno R3 Development Board',
    price: 1299,
    image: 'https://images.pexels.com/photos/159304/network-cable-ethernet-computer-159304.jpeg',
    category: 'controllers',
    rating: 4.8,
    reviews: 245,
    inStock: true,
    description: 'The Arduino Uno R3 is a microcontroller board based on the ATmega328P. It has 14 digital input/output pins, 6 analog inputs, a 16 MHz quartz crystal, a USB connection, and more.',
    discount: 15,
  },
  {
    id: '2',
    name: 'Raspberry Pi 4 Model B',
    price: 4299,
    image: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg',
    category: 'controllers',
    rating: 4.9,
    reviews: 189,
    inStock: true,
    description: 'The Raspberry Pi 4 Model B is the newest Raspberry Pi computer made, and the Pi Foundation knows you can always make a good thing better!',
    discount: 10,
  },
  {
    id: '3',
    name: 'Ultrasonic Distance Sensor HC-SR04',
    price: 299,
    image: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg',
    category: 'sensors',
    rating: 4.6,
    reviews: 312,
    inStock: true,
    description: 'HC-SR04 ultrasonic sensor provides 2cm - 400cm non-contact measurement function with ranging accuracy up to 3mm.',
  },
  {
    id: '4',
    name: 'Servo Motor SG90',
    price: 399,
    image: 'https://images.pexels.com/photos/356056/pexels-photo-356056.jpeg',
    category: 'actuators',
    rating: 4.4,
    reviews: 178,
    inStock: true,
    description: 'SG90 9g micro servo motor with accessories for Arduino and other microcontroller projects.',
    discount: 20,
  },
  {
    id: '5',
    name: 'ESP32 WiFi Bluetooth Module',
    price: 899,
    image: 'https://images.pexels.com/photos/325229/pexels-photo-325229.jpeg',
    category: 'electronics',
    rating: 4.7,
    reviews: 156,
    inStock: true,
    description: 'ESP32 is a series of low-cost, low-power system on a chip microcontrollers with integrated Wi-Fi and dual-mode Bluetooth.',
  },
  {
    id: '6',
    name: 'Temperature Humidity Sensor DHT22',
    price: 599,
    image: 'https://images.pexels.com/photos/442152/pexels-photo-442152.jpeg',
    category: 'sensors',
    rating: 4.5,
    reviews: 203,
    inStock: false,
    description: 'DHT22 digital temperature and humidity sensor with high accuracy and stability.',
    discount: 5,
  },
  {
    id: '7',
    name: 'Stepper Motor NEMA 17',
    price: 1599,
    image: 'https://images.pexels.com/photos/159298/gears-cogs-machine-machinery-159298.jpeg',
    category: 'actuators',
    rating: 4.8,
    reviews: 89,
    inStock: true,
    description: 'NEMA 17 stepper motor perfect for 3D printers, CNC machines, and robotics projects.',
  },
  {
    id: '8',
    name: 'LED Strip 5050 RGB',
    price: 799,
    image: 'https://images.pexels.com/photos/358235/pexels-photo-358235.jpeg',
    category: 'electronics',
    rating: 4.3,
    reviews: 267,
    inStock: true,
    description: '5050 RGB LED strip with 60 LEDs per meter, waterproof and suitable for decoration and automation projects.',
    discount: 25,
  },
];

export const featuredProducts = sampleProducts.slice(0, 4);
export const bestSellers = sampleProducts.filter(p => p.reviews > 200);
export const newArrivals = sampleProducts.slice(-3);

export const banners = [
  {
    id: '1',
    title: 'Smart Automation Solutions',
    subtitle: 'Transform your projects with cutting-edge technology',
    image: 'https://images.pexels.com/photos/373543/pexels-photo-373543.jpeg',
    cta: 'Shop Now',
    link: '/products',
  },
  {
    id: '2',
    title: 'New Arduino Collection',
    subtitle: 'Latest development boards and accessories',
    image: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg',
    cta: 'Explore',
    link: '/products?category=controllers',
  },
  {
    id: '3',
    title: 'Sensor Sale - Up to 30% Off',
    subtitle: 'High-precision sensors for your next project',
    image: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg',
    cta: 'Save Now',
    link: '/products?category=sensors',
  },
];

export const testimonials = [
  {
    id: '1',
    name: 'Rajesh Kumar',
    role: 'Automation Engineer',
    content: 'RoboSemi has the best quality components at competitive prices. Fast delivery and excellent customer service.',
    avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg',
    rating: 5,
  },
  {
    id: '2',
    name: 'Priya Sharma',
    role: 'IoT Developer',
    content: 'Great platform for all my electronics needs. The product descriptions are detailed and shipping is always on time.',
    avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg',
    rating: 5,
  },
  {
    id: '3',
    name: 'Amit Patel',
    role: 'Robotics Student',
    content: 'Perfect for students and professionals alike. Wide range of products and helpful documentation.',
    avatar: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg',
    rating: 5,
  },
];